# Generated by Django 4.2 on 2023-07-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('tax_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.TextField(blank=True)),
                ('scientific_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sequence', models.TextField(blank=True)),
                ('length', models.IntegerField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organism')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_coordinate', models.IntegerField()),
                ('end_coordinate', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.protein')),
            ],
        ),
    ]
