# Generated by Django 4.2 on 2023-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tax_id_organism_taxa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='scientific_name',
            new_name='genus_species',
        ),
    ]
