# Generated by Django 4.2 on 2023-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_scientific_name_organism_genus_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='clade',
            new_name='clade_id',
        ),
    ]
